//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reShutCLI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("reShutCLI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About reShut CLI.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to main menu.
        /// </summary>
        internal static string BackToMainMenu {
            get {
                return ResourceManager.GetString("BackToMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure? Press any key to continue..
        /// </summary>
        internal static string ConfirmationText {
            get {
                return ResourceManager.GetString("ConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reShut CLI .
        /// </summary>
        internal static string ConsoleTitle {
            get {
                return ResourceManager.GetString("ConsoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2023-2026 elNino0916 and contributors..
        /// </summary>
        internal static string CopyrightText {
            get {
                return ResourceManager.GetString("CopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Double-Confirmation.
        /// </summary>
        internal static string DoubleConfiguration {
            get {
                return ResourceManager.GetString("DoubleConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-Confirmation is disabled..
        /// </summary>
        internal static string DoubleConfirmOff {
            get {
                return ResourceManager.GetString("DoubleConfirmOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-Confirmation is enabled..
        /// </summary>
        internal static string DoubleConfirmOn {
            get {
                return ResourceManager.GetString("DoubleConfirmOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This interface is currently being improved. Please report any bugs on GitHub..
        /// </summary>
        internal static string ErrorHandler_BeingImproved {
            get {
                return ResourceManager.GetString("ErrorHandler_BeingImproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↵ Press any key to return to Settings..
        /// </summary>
        internal static string ErrorHandler_PressKeyBack {
            get {
                return ResourceManager.GetString("ErrorHandler_PressKeyBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↵ Press any key to restart reShut CLI..
        /// </summary>
        internal static string ErrorHandler_PressKeyRestart {
            get {
                return ResourceManager.GetString("ErrorHandler_PressKeyRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred..
        /// </summary>
        internal static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help translate reShut CLI to your language!.
        /// </summary>
        internal static string HelpTranslate {
            get {
                return ResourceManager.GetString("HelpTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input..
        /// </summary>
        internal static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license is available at: https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode.en.
        /// </summary>
        internal static string LicenseText {
            get {
                return ResourceManager.GetString("LicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logoff.
        /// </summary>
        internal static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu and Texts.
        /// </summary>
        internal static string MenuAndText {
            get {
                return ResourceManager.GetString("MenuAndText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reShut CLI needs to restart..
        /// </summary>
        internal static string NeedRestart {
            get {
                return ResourceManager.GetString("NeedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Release .
        /// </summary>
        internal static string PreRelease {
            get {
                return ResourceManager.GetString("PreRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↵ Press any key to go back..
        /// </summary>
        internal static string PressAnyKeyToGoBack {
            get {
                return ResourceManager.GetString("PressAnyKeyToGoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot.
        /// </summary>
        internal static string Reboot {
            get {
                return ResourceManager.GetString("Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry Version.
        /// </summary>
        internal static string RegistryVersion {
            get {
                return ResourceManager.GetString("RegistryVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating registry....
        /// </summary>
        internal static string RegUpdate {
            get {
                return ResourceManager.GetString("RegUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all settings.
        /// </summary>
        internal static string ResetAllSettings {
            get {
                return ResourceManager.GetString("ResetAllSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset in progress. Do not close reShut CLI....
        /// </summary>
        internal static string ResetProg {
            get {
                return ResourceManager.GetString("ResetProg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to reset reShut CLI? This cannot be undone!.
        /// </summary>
        internal static string ResetWarning {
            get {
                return ResourceManager.GetString("ResetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule....
        /// </summary>
        internal static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action has been cancelled..
        /// </summary>
        internal static string Schedule_ActionCancelled {
            get {
                return ResourceManager.GetString("Schedule_ActionCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action has been scheduled!.
        /// </summary>
        internal static string Schedule_ActionScheduled {
            get {
                return ResourceManager.GetString("Schedule_ActionScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel schedule.
        /// </summary>
        internal static string Schedule_Cancel {
            get {
                return ResourceManager.GetString("Schedule_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to schedule a {0} in {1} minute(s). Is that correct?.
        /// </summary>
        internal static string Schedule_ConfirmActionSeconds {
            get {
                return ResourceManager.GetString("Schedule_ConfirmActionSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, go back and re-enter information..
        /// </summary>
        internal static string Schedule_ConfirmNoReenter {
            get {
                return ResourceManager.GetString("Schedule_ConfirmNoReenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, schedule {0}.
        /// </summary>
        internal static string Schedule_ConfirmYes {
            get {
                return ResourceManager.GetString("Schedule_ConfirmYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current time:.
        /// </summary>
        internal static string Schedule_CurrentTime {
            get {
                return ResourceManager.GetString("Schedule_CurrentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the time in minutes..
        /// </summary>
        internal static string Schedule_EnterSeconds {
            get {
                return ResourceManager.GetString("Schedule_EnterSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Input must be a valid number..
        /// </summary>
        internal static string Schedule_ErrorNumberInput {
            get {
                return ResourceManager.GetString("Schedule_ErrorNumberInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input:.
        /// </summary>
        internal static string Schedule_InputPrompt {
            get {
                return ResourceManager.GetString("Schedule_InputPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to schedule?.
        /// </summary>
        internal static string Schedule_PromptAction {
            get {
                return ResourceManager.GetString("Schedule_PromptAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When should the action be executed?.
        /// </summary>
        internal static string Schedule_PromptWhen {
            get {
                return ResourceManager.GetString("Schedule_PromptWhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot.
        /// </summary>
        internal static string Schedule_RebootOption {
            get {
                return ResourceManager.GetString("Schedule_RebootOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an option:.
        /// </summary>
        internal static string Schedule_SelectOption {
            get {
                return ResourceManager.GetString("Schedule_SelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        internal static string Schedule_ShutdownOption {
            get {
                return ResourceManager.GetString("Schedule_ShutdownOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}hrs).
        /// </summary>
        internal static string Schedule_TimeBreakdown {
            get {
                return ResourceManager.GetString("Schedule_TimeBreakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the language you would like to use..
        /// </summary>
        internal static string SelectLang {
            get {
                return ResourceManager.GetString("SelectLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a theme to personalize your experience..
        /// </summary>
        internal static string SelectTheme {
            get {
                return ResourceManager.GetString("SelectTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        internal static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup.
        /// </summary>
        internal static string Startup {
            get {
                return ResourceManager.GetString("Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update for reShut CLI is available. Press U to update..
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check for updates. Check your network connection and try again..
        /// </summary>
        internal static string UpdateCheckFailed {
            get {
                return ResourceManager.GetString("UpdateCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download started, Installer will open in a few seconds....
        /// </summary>
        internal static string UpdateDLStarted {
            get {
                return ResourceManager.GetString("UpdateDLStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reShut CLI Updater.
        /// </summary>
        internal static string UpdaterTitle {
            get {
                return ResourceManager.GetString("UpdaterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Search is disabled..
        /// </summary>
        internal static string UpdatesDisabled {
            get {
                return ResourceManager.GetString("UpdatesDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Search is disabled..
        /// </summary>
        internal static string UpdateSearchDisabled {
            get {
                return ResourceManager.GetString("UpdateSearchDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Update is disabled..
        /// </summary>
        internal static string UpdateSettings_AutoUpdateDisabled {
            get {
                return ResourceManager.GetString("UpdateSettings_AutoUpdateDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Update is enabled..
        /// </summary>
        internal static string UpdateSettings_AutoUpdateEnabled {
            get {
                return ResourceManager.GetString("UpdateSettings_AutoUpdateEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Settings.
        /// </summary>
        internal static string UpdateSettings_Title {
            get {
                return ResourceManager.GetString("UpdateSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Auto Update on Startup.
        /// </summary>
        internal static string UpdateSettings_ToggleAutoUpdate {
            get {
                return ResourceManager.GetString("UpdateSettings_ToggleAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Update Search.
        /// </summary>
        internal static string UpdateSettings_ToggleUpdateSearch {
            get {
                return ResourceManager.GetString("UpdateSettings_ToggleUpdateSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Search is disabled..
        /// </summary>
        internal static string UpdateSettings_UpdateSearchDisabled {
            get {
                return ResourceManager.GetString("UpdateSettings_UpdateSearchDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Search is enabled..
        /// </summary>
        internal static string UpdateSettings_UpdateSearchEnabled {
            get {
                return ResourceManager.GetString("UpdateSettings_UpdateSearchEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reShut CLI is up to date!.
        /// </summary>
        internal static string UpToDate {
            get {
                return ResourceManager.GetString("UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
