//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reShutCLI.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("reShutCLI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About reShut CLI ähnelt.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back to main menu ähnelt.
        /// </summary>
        internal static string BackToMainMenu {
            get {
                return ResourceManager.GetString("BackToMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure? Press any key to continue. ähnelt.
        /// </summary>
        internal static string ConfirmationText {
            get {
                return ResourceManager.GetString("ConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die reShut CLI  ähnelt.
        /// </summary>
        internal static string ConsoleTitle {
            get {
                return ResourceManager.GetString("ConsoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copyright © 2023-2025 elNino0916 ähnelt.
        /// </summary>
        internal static string CopyrightText {
            get {
                return ResourceManager.GetString("CopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle Double-Confirmation ähnelt.
        /// </summary>
        internal static string DoubleConfiguration {
            get {
                return ResourceManager.GetString("DoubleConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Double-Confirmation is disabled. ähnelt.
        /// </summary>
        internal static string DoubleConfirmOff {
            get {
                return ResourceManager.GetString("DoubleConfirmOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Double-Confirmation is enabled. ähnelt.
        /// </summary>
        internal static string DoubleConfirmOn {
            get {
                return ResourceManager.GetString("DoubleConfirmOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This interface is currently being improved. Please report any bugs on GitHub. ähnelt.
        /// </summary>
        internal static string ErrorHandler_BeingImproved {
            get {
                return ResourceManager.GetString("ErrorHandler_BeingImproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ↵ Press any key to return to Settings. ähnelt.
        /// </summary>
        internal static string ErrorHandler_PressKeyBack {
            get {
                return ResourceManager.GetString("ErrorHandler_PressKeyBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ↵ Press any key to restart reShut CLI. ähnelt.
        /// </summary>
        internal static string ErrorHandler_PressKeyRestart {
            get {
                return ResourceManager.GetString("ErrorHandler_PressKeyRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occurred. ähnelt.
        /// </summary>
        internal static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help translate reShut CLI to your language! ähnelt.
        /// </summary>
        internal static string HelpTranslate {
            get {
                return ResourceManager.GetString("HelpTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid input. ähnelt.
        /// </summary>
        internal static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The license is available at: https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode.en ähnelt.
        /// </summary>
        internal static string LicenseText {
            get {
                return ResourceManager.GetString("LicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logoff ähnelt.
        /// </summary>
        internal static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Main Menu ähnelt.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Menu and Texts ähnelt.
        /// </summary>
        internal static string MenuAndText {
            get {
                return ResourceManager.GetString("MenuAndText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die reShut CLI needs to restart. ähnelt.
        /// </summary>
        internal static string NeedRestart {
            get {
                return ResourceManager.GetString("NeedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pre-Release  ähnelt.
        /// </summary>
        internal static string PreRelease {
            get {
                return ResourceManager.GetString("PreRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ↵ Press any key to go back. ähnelt.
        /// </summary>
        internal static string PressAnyKeyToGoBack {
            get {
                return ResourceManager.GetString("PressAnyKeyToGoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quit ähnelt.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reboot ähnelt.
        /// </summary>
        internal static string Reboot {
            get {
                return ResourceManager.GetString("Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registry Version ähnelt.
        /// </summary>
        internal static string RegistryVersion {
            get {
                return ResourceManager.GetString("RegistryVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Updating registry... ähnelt.
        /// </summary>
        internal static string RegUpdate {
            get {
                return ResourceManager.GetString("RegUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset all settings ähnelt.
        /// </summary>
        internal static string ResetAllSettings {
            get {
                return ResourceManager.GetString("ResetAllSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset in progress. Do not close reShut CLI... ähnelt.
        /// </summary>
        internal static string ResetProg {
            get {
                return ResourceManager.GetString("ResetProg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to reset reShut CLI? This cannot be undone! ähnelt.
        /// </summary>
        internal static string ResetWarning {
            get {
                return ResourceManager.GetString("ResetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schedule... ähnelt.
        /// </summary>
        internal static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Action has been cancelled. ähnelt.
        /// </summary>
        internal static string Schedule_ActionCancelled {
            get {
                return ResourceManager.GetString("Schedule_ActionCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Action has been scheduled! ähnelt.
        /// </summary>
        internal static string Schedule_ActionScheduled {
            get {
                return ResourceManager.GetString("Schedule_ActionScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel schedule ähnelt.
        /// </summary>
        internal static string Schedule_Cancel {
            get {
                return ResourceManager.GetString("Schedule_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You want to schedule a {0} in {1} minute(s). Is that correct? ähnelt.
        /// </summary>
        internal static string Schedule_ConfirmActionSeconds {
            get {
                return ResourceManager.GetString("Schedule_ConfirmActionSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No, go back and re-enter information. ähnelt.
        /// </summary>
        internal static string Schedule_ConfirmNoReenter {
            get {
                return ResourceManager.GetString("Schedule_ConfirmNoReenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes, schedule {0} ähnelt.
        /// </summary>
        internal static string Schedule_ConfirmYes {
            get {
                return ResourceManager.GetString("Schedule_ConfirmYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current time: ähnelt.
        /// </summary>
        internal static string Schedule_CurrentTime {
            get {
                return ResourceManager.GetString("Schedule_CurrentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the time in minutes. ähnelt.
        /// </summary>
        internal static string Schedule_EnterSeconds {
            get {
                return ResourceManager.GetString("Schedule_EnterSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error: Input must be a valid number. ähnelt.
        /// </summary>
        internal static string Schedule_ErrorNumberInput {
            get {
                return ResourceManager.GetString("Schedule_ErrorNumberInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input: ähnelt.
        /// </summary>
        internal static string Schedule_InputPrompt {
            get {
                return ResourceManager.GetString("Schedule_InputPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die What would you like to schedule? ähnelt.
        /// </summary>
        internal static string Schedule_PromptAction {
            get {
                return ResourceManager.GetString("Schedule_PromptAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When should the action be executed? ähnelt.
        /// </summary>
        internal static string Schedule_PromptWhen {
            get {
                return ResourceManager.GetString("Schedule_PromptWhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reboot ähnelt.
        /// </summary>
        internal static string Schedule_RebootOption {
            get {
                return ResourceManager.GetString("Schedule_RebootOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select an option: ähnelt.
        /// </summary>
        internal static string Schedule_SelectOption {
            get {
                return ResourceManager.GetString("Schedule_SelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shutdown ähnelt.
        /// </summary>
        internal static string Schedule_ShutdownOption {
            get {
                return ResourceManager.GetString("Schedule_ShutdownOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ({0}hrs) ähnelt.
        /// </summary>
        internal static string Schedule_TimeBreakdown {
            get {
                return ResourceManager.GetString("Schedule_TimeBreakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the language you would like to use. ähnelt.
        /// </summary>
        internal static string SelectLang {
            get {
                return ResourceManager.GetString("SelectLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select a theme to personalize your experience. ähnelt.
        /// </summary>
        internal static string SelectTheme {
            get {
                return ResourceManager.GetString("SelectTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shutdown ähnelt.
        /// </summary>
        internal static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Startup ähnelt.
        /// </summary>
        internal static string Startup {
            get {
                return ResourceManager.GetString("Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Theme ähnelt.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Updates ähnelt.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An update for reShut CLI is available. Press U to update. ähnelt.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to check for updates. Check your network connection and try again. ähnelt.
        /// </summary>
        internal static string UpdateCheckFailed {
            get {
                return ResourceManager.GetString("UpdateCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download started, Installer will open in a few seconds... ähnelt.
        /// </summary>
        internal static string UpdateDLStarted {
            get {
                return ResourceManager.GetString("UpdateDLStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die reShut CLI Updater ähnelt.
        /// </summary>
        internal static string UpdaterTitle {
            get {
                return ResourceManager.GetString("UpdaterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Search is disabled. ähnelt.
        /// </summary>
        internal static string UpdatesDisabled {
            get {
                return ResourceManager.GetString("UpdatesDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Search is disabled. ähnelt.
        /// </summary>
        internal static string UpdateSearchDisabled {
            get {
                return ResourceManager.GetString("UpdateSearchDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto Update is disabled. ähnelt.
        /// </summary>
        internal static string UpdateSettings_AutoUpdateDisabled {
            get {
                return ResourceManager.GetString("UpdateSettings_AutoUpdateDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto Update is enabled. ähnelt.
        /// </summary>
        internal static string UpdateSettings_AutoUpdateEnabled {
            get {
                return ResourceManager.GetString("UpdateSettings_AutoUpdateEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Settings ähnelt.
        /// </summary>
        internal static string UpdateSettings_Title {
            get {
                return ResourceManager.GetString("UpdateSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle Auto Update on Startup ähnelt.
        /// </summary>
        internal static string UpdateSettings_ToggleAutoUpdate {
            get {
                return ResourceManager.GetString("UpdateSettings_ToggleAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle Update Search ähnelt.
        /// </summary>
        internal static string UpdateSettings_ToggleUpdateSearch {
            get {
                return ResourceManager.GetString("UpdateSettings_ToggleUpdateSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Search is disabled. ähnelt.
        /// </summary>
        internal static string UpdateSettings_UpdateSearchDisabled {
            get {
                return ResourceManager.GetString("UpdateSettings_UpdateSearchDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Search is enabled. ähnelt.
        /// </summary>
        internal static string UpdateSettings_UpdateSearchEnabled {
            get {
                return ResourceManager.GetString("UpdateSettings_UpdateSearchEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die reShut CLI is up to date! ähnelt.
        /// </summary>
        internal static string UpToDate {
            get {
                return ResourceManager.GetString("UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
